### ISSUE TITLE
GetViewerList and GetActiveUsers bugged for YouTube

### ISSUE THREAD

**Issue by Anders-Lunde** [AnkhHeart/Streamlabs-Chatbot-Python-Boilerplate#5]
Both requests seems to behave a bit randomly and doesnt list all the people in the chat. Both of them seem to only react to active users. I really wish GetViewerList  worked at least. Also, when people join the chat, it takes a few mins before the GetViewerList sees them. And I think in some cases they have to chat to be detected. Also, if they are inactive, they decay from the lists quite fast.

**Comment by AnkhHeart** [comment]
The youtube API does not have an actual viewerlist so it is normal for both to behave the same. It's just based off of activity.
